# Generated by Django 3.1 on 2020-08-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='anoPublicacao',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='emailEditora',
            field=models.EmailField(default='0', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.IntegerField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='numeroPagina',
            field=models.IntegerField(default='default'),
            preserve_default=False,
        ),
    ]
