# Generated by Django 3.1 on 2020-09-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='anoPublicacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livro',
            name='emailEditora',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livro',
            name='numeroPaginas',
            field=models.IntegerField(default=0),
        ),
    ]
