# Generated by Django 3.1 on 2020-08-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_auto_20200822_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='anoPublicacao',
            field=models.IntegerField(default=0),
        ),
    ]
