# Generated by Django 3.1 on 2020-08-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_auto_20200824_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='anoPublicacao',
            field=models.IntegerField(),
        ),
    ]
